### PR TITLE
added mybatis.configuration.defaultStatementTimeout inject property in C...

### PR DESCRIPTION
**Pull request by littson**
...onfigurationProvider.

### CODE REVIEW

**Comment by christianpoitras** [comment]
Thanks!
But calling setDefaultStatementTimeout(null) result in an NPE in the bindConstant() call.

Can you fix that, please?
Use bind(Integer.class) instead of bindConstant().

**Comment by littson** [comment]
Thanks for the feedback.

The `bindConstant()` call works fine in my setup.  Which version of Guice are you using? (I am using Guice `com.google.inject:guice:3.0`.)

I would like to fix it if I can reproduce the problem.

**Comment by christianpoitras** [comment]
I didn't try it, but I'll add a unit test for it, just in case.

I assumed that an NPE would be thrown when setting null because the to() method takes an int rather than an Integer. See http://google.github.io/guice/api-docs/3.0/javadoc/com/google/inject/binder/ConstantBindingBuilder.html

**Comment by littson** [comment]
Sorry, I just realized what's your meaning in the first commit. You were right, the `setDefaultStatementTimeout(null)` would raise an NPE. 

However, I think the use of `bindConstant()` method is OK. Following are quoted from [Binder example docs](http://google.github.io/guice/api-docs/3.0/javadoc/com/google/inject/Binder.html): 

> bindConstant().annotatedWith(ServerHost.class).to(args[0]);
> Sets up a constant binding. Constant injections must always be annotated. When a constant binding's value is a string, it is eligile for conversion to all primitive types, to all enums, and to class literals. Conversions for other types can be configured using convertToTypes().

And I have made following changes to make the code more robust:

1. Rename setter method from `defaultStatementTimeout` to `setDefaultStatementTimeout`.
2. Change defaultStatementTimeout type to primitive int.
3. Add validation in setDefaultStatementTimeout().

**Comment by christianpoitras** [comment]
I would prefer that the methods match the Configuration class from MyBatis. For example, if MyBatis default value would change to a non null value, users should be able to force a null value for statement timeout (thus disabling timeout). Your current code does not allow this.

Also, the name defaultStatementTimeout is better since it matches the other method names.

Thanks!

**Comment by littson** [comment]
Your comment is reasonable. I have updated the code with following changes:

1. Use `Integer` instead of `int` to allow null values. 
2. Use `bind(Integer.class)` as you suggested (and thanks for the hint).
3. Rename setter method setDefaultStatementTimeout to defaultStatementTimeout.
4. Add dependency to com.google.code.findbugs:jsr305:3.0.0 to use `javax.annotation.Nullable`.

The use of `Nullable` is required per [guice wiki](https://github.com/google/guice/wiki/UseNullable):

> Guice forbids null by default. It will refuse to inject null, failing with a ProvisionException instead. If null is permissible by your class, you can annotate the field or parameter with @Nullable. Guice recognizes any @Nullable annotation, like edu.umd.cs.findbugs.annotations.Nullable or javax.annotation.Nullable.

**Comment by christianpoitras** [comment]
Great! I'll merge your commit.

I'll probably mark the jsr305 dependency as optional since it is only required for a specific case.

Thanks for the work!

**Pull request merged**
